image: python:3.5.7

pipelines:
  branches:
    develop:
      - step: # second step is for deploy the artifact
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for deploy_toS3.py
            - zip -r /tmp/artifact.zip . # package up the application for deployment
            - python s3_upload.py # run the deployment script
    staging:
      - step: # second step is for deploy the artifact
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for deploy_toS3.py
            - zip -r /tmp/artifact.zip . # package up the application for deployment
            - python s3_upload_stg.py # run the deployment script