export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';

export const CREATE_CONTACTS = 'CREATE_CONTACTS';
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const CREATE_CONTACTS_FAILED = 'CREATE_CONTACTS_FAILED';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const DELETE_CONTACTS = 'DELETE_CONTACTS';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAILED = 'DELETE_CONTACTS_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_CONTACT_ID = 'GET_CONTACT_ID';
export const GET_CONTACT_ID_SUCCESS = 'GET_CONTACT_ID_SUCCESS';
export const GET_CONTACT_ID_FAILED = 'GET_CONTACT_ID_FAILED';

export const GET_CONTACT_RUT = 'GET_CONTACT_RUT';
export const GET_CONTACT_RUT_SUCCESS = 'GET_CONTACT_RUT_SUCCESS';
export const GET_CONTACT_ID_SUCCESS_EMPTY = 'GET_CONTACT_ID_SUCCESS_EMPTY';
export const GET_CONTACT_RUT_FAILED = 'GET_CONTACT_RUT_FAILED';
export const GET_CONTRACT_BY_RUT = 'GET_CONTRACT_BY_RUT';
export const GET_CONTRACT_BY_RUT_SUCCESS = 'GET_CONTRACT_BY_RUT_SUCCESS';
export const GET_CONTRACT_BY_RUT_FAILED = 'GET_CONTRACT_BY_RUT_FAILED';
export const RESET_CONTACT_STATE = 'RESET_CONTACT_STATE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';

export const GET_SUMMARY_CASES = 'GET_SUMMARY_CASES';
export const GET_SUMMARY_CASES_SUCCESS = 'GET_SUMMARY_CASES_SUCCESS';
export const GET_SUMMARY_CASES_FAILED = 'GET_SUMMARY_CASES_FAILED';

export const GET_SUMMARY_QUOTATIONS = 'GET_SUMMARY_QUOTATIONS';
export const GET_SUMMARY_QUOTATIONS_SUCCESS = 'GET_SUMMARY_QUOTATIONS_SUCCESS';
export const GET_SUMMARY_QUOTATIONS_FAILED = 'GET_SUMMARY_QUOTATIONS_FAILED';

export const CREATE_CASE = 'CREATE_CASE';
export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS';
export const CREATE_CASE_FAILED = 'CREATE_CASE_FAILED';

export const GET_CASE_ID = 'GET_CASE_ID';
export const GET_CASE_ID_SUCCESS = 'GET_CASE_ID_SUCCESS';
export const GET_CASE_ID_FAILED = 'GET_CASE_ID_FAILED';

export const DELETE_CASE = 'DELETE_CASE';
export const DELETE_CASE_SUCCESS = 'DELETE_CASE_SUCCESS';
export const DELETE_CASE_FAILED = 'DELETE_CASE_FAILED';

export const GET_ALL_CASE = 'GET_ALL_CASE';
export const GET_ALL_CASE_SUCCESS = 'GET_ALL_CASE_SUCCESS';
export const GET_ALL_CASE_FAILED = 'GET_ALL_CASE_FAILED';

export const GET_ALL_CASE_DASHBOARD = 'GET_ALL_CASE_DASHBOARD';
export const GET_ALL_CASE_DASHBOARD_SUCCESS = 'GET_ALL_CASE_DASHBOARD_SUCCESS';
export const GET_ALL_CASE_DASHBOARD_FAILED = 'GET_ALL_CASE_DASHBOARD_FAILED';

export const UPDATE_CASE = 'UPDATE_CASE';
export const UPDATE_CASE_SUCCESS = 'UPDATE_CASE_SUCCESS';
export const UPDATE_CASE_FAILED = 'UPDATE_CASE_FAILED';

export const UPDATE_CASE_MANY = 'UPDATE_CASE_MANY';
export const UPDATE_CASE_MANY_SUCCESS = 'UPDATE_CASE_MANY_SUCCESS';
export const UPDATE_CASE_MANY_FAILED = 'UPDATE_CASE_MANY_FAILED';


export const GET_TYPES = 'GET_TYPES';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAILED = 'GET_TYPES_FAILED';

export const CREATE_SUBCASE = 'CREATE_SUBCASE';
export const CREATE_SUBCASE_SUCCESS = 'CREATE_SUBCASE_SUCCESS';
export const CREATE_SUBCASE_FAILED = 'CREATE_SUBCASE_FAILED';

export const UPDATE_SUBCASE = 'UPDATE_SUBCASE';
export const UPDATE_SUBCASE_SUCCESS = 'UPDATE_SUBCASE_SUCCESS';
export const UPDATE_SUBCASE_FAILED = 'UPDATE_SUBCASE_FAILED';

export const DELETE_SUBCASE = 'DELETE_SUBCASE';
export const DELETE_SUBCASE_SUCCESS = 'DELETE_SUBCASE_SUCCESS';
export const DELETE_SUBCASE_FAILED = 'DELETE_SUBCASE_FAILED';

export const GET_SUBTYPES = 'GET_SUBTYPES';
export const GET_SUBTYPES_SUCCESS = 'GET_SUBTYPES_SUCCESS';
export const GET_SUBTYPES_FAILED = 'GET_SUBTYPES_FAILED';

export const GET_ALL_QUOTATIONS = 'GET_ALL_QUOTATIONS';
export const GET_ALL_QUOTATIONS_SUCCESS = 'GET_ALL_QUOTATIONS_SUCCESS';
export const GET_ALL_QUOTATIONS_FAILED = 'GET_ALL_QUOTATIONS_FAILED';

export const GET_ALL_QUOTATIONS_DASHBOARD = 'GET_ALL_QUOTATIONS_DASHBOARD';
export const GET_ALL_QUOTATIONS_DASHBOARD_SUCCESS = 'GET_ALL_QUOTATIONS_DASHBOARD_SUCCESS';
export const GET_ALL_QUOTATIONS_DASHBOARD_FAILED = 'GET_ALL_QUOTATIONS_DASHBOARD_FAILED';

export const CREATE_QUOTATIONS = 'CREATE_QUOTATIONS';
export const CREATE_QUOTATIONS_SUCCESS = 'CREATE_QUOTATIONS_SUCCESS';
export const CREATE_QUOTATIONS_FAILED = 'CREATE_QUOTATIONS_FAILED';

export const SEND_FORM = 'SEND_FORM';
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS';
export const SEND_FORM_FAILED = 'SEND_FORM_FAILED';

export const GET_ALL_REGIONS = 'GET_ALL_REGIONS';
export const GET_ALL_REGIONS_SUCCESS = 'GET_ALL_REGIONS_SUCCESS';
export const GET_ALL_REGIONS_FAILED = 'GET_ALL_REGIONS_FAILED';

export const GET_SETTING = 'GET_SETTING';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';

export const GET_SETTING_URL_CUSTOMER_SERVICE = 'GET_SETTING_URL_CUSTOMER_SERVICE';
export const GET_SETTING_URL_CUSTOMER_SERVICE_SUCCESS = 'GET_SETTING_URL_CUSTOMER_SERVICE_SUCCESS';
export const GET_SETTING_URL_CUSTOMER_SERVICE_FAILED = 'GET_SETTING_URL_CUSTOMER_SERVICE_FAILED';

export const GET_SETTING_URL_PRE_PAID = 'GET_SETTING_URL_PRE_PAID';
export const GET_SETTING_URL_PRE_PAID_SUCCESS = 'GET_SETTING_URL_PRE_PAID_SUCCESS';
export const GET_SETTING_URL_PRE_PAID_FAILED = 'GET_SETTING_URL_PRE_PAID_FAILED';

export const PUT_PRE_PAID = 'PUT_PRE_PAID';
export const PUT_PRE_PAID_SUCCESS = 'PUT_PRE_PAID_SUCCESS';
export const PUT_PRE_PAID_FAILED = 'PUT_PRE_PAID_FAILED';

export const GET_SETTING_URL_PRE_PAID_INTERNAL = 'GET_SETTING_URL_PRE_PAID_INTERNAL';
export const GET_SETTING_URL_PRE_PAID_INTERNAL_SUCCESS = 'GET_SETTING_URL_PRE_PAID_INTERNAL_SUCCESS';
export const GET_SETTING_URL_PRE_PAID_INTERNAL_FAILED = 'GET_SETTING_URL_PRE_PAID_INTERNAL_FAILED';

export const GET_ALL_ROLLS = 'GET_ALL_ROLLS';
export const GET_ALL_ROLLS_SUCCESS = 'GET_ALL_ROLLS_SUCCESS';
export const GET_ALL_ROLLS_FAILED = 'GET_ALL_ROLLS_FAILED';

export const GET_SEXES = 'GET_SEXES';
export const GET_SEXES_SUCCESS = 'GET_SEXES_SUCCESS';
export const GET_SEXES_FAILED = 'GET_SEXES_FAILED';

export const GET_NATIONALITIES = 'GET_NATIONALITIES';
export const GET_NATIONALITIES_SUCCESS = 'GET_NATIONALITIES_SUCCESS';
export const GET_NATIONALITIES_FAILED = 'GET_NATIONALITIES_FAILED';

export const GET_CIVILSTATUS = 'GET_CIVILSTATUS';
export const GET_CIVILSTATUS_SUCCESS = 'GET_CIVILSTATUS_SUCCESS';
export const GET_CIVILSTATUS_FAILED = 'GET_CIVILSTATUS_FAILED';

export const GET_ALL_COMMUNS = 'GET_ALL_COMMUNS';
export const GET_ALL_COMMUNS_SUCCESS = 'GET_ALL_COMMUNS_SUCCESS';
export const GET_ALL_COMMUNS_FAILED = 'GET_ALL_COMMUNS_FAILED';

export const GET_QUOTATIONS_ID = 'GET_QUOTATIONS_ID';
export const GET_QUOTATIONS_ID_SUCCESS = 'GET_QUOTATIONS_ID_SUCCESS';
export const GET_QUOTATIONS_ID_FAILED = 'GET_QUOTATIONS_ID_FAILED';

export const UPDATE_QUOTATIONS = 'UPDATE_QUOTATIONS';
export const UPDATE_QUOTATIONS_SUCCESS = 'UPDATE_QUOTATIONS_SUCCESS';
export const UPDATE_QUOTATIONS_FAILED = 'UPDATE_QUOTATIONS_FAILED';

export const UPDATE_QUOTATION_MANY = 'UPDATE_QUOTATION_MANY';
export const UPDATE_QUOTATION_MANY_SUCCESS = 'UPDATE_QUOTATION_MANY_SUCCESS';
export const UPDATE_QUOTATION_MANY_FAILED = 'UPDATE_QUOTATION_MANY_FAILED';

export const DELETE_QUOTATIONS = 'DELETE_QUOTATIONS';
export const DELETE_QUOTATIONS_SUCCESS = 'DELETE_QUOTATIONS_SUCCESS';
export const DELETE_QUOTATIONS_FAILED = 'DELETE_QUOTATIONS_FAILED';

export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_FAILED = 'GET_ALL_NOTIFICATIONS_FAILED';


export const CREATE_EMAIL_TEMPLATE = 'CREATE_EMAIL_TEMPLATE';
export const CREATE_EMAIL_TEMPLATE_SUCCESS = 'CREATE_EMAIL_TEMPLATE_SUCCESS';
export const CREATE_EMAIL_TEMPLATE_FAILED = 'CREATE_EMAIL_TEMPLATE_FAILED';

export const GET_EMAIL_TEMPLATE = 'GET_EMAIL_TEMPLATE';
export const GET_EMAIL_TEMPLATE_SUCCESS = 'GET_EMAIL_TEMPLATE_SUCCESS';
export const GET_EMAIL_TEMPLATE_FAILED = 'GET_EMAIL_TEMPLATE_FAILED';

export const GET_EMAIL_TEMPLATE_ID = 'GET_EMAIL_TEMPLATE_ID';
export const GET_EMAIL_TEMPLATE_ID_SUCCESS = 'GET_EMAIL_TEMPLATE_ID_SUCCESS';
export const GET_EMAIL_TEMPLATE_ID_FAILED = 'GET_EMAIL_TEMPLATE_ID_FAILED';

export const UPDATE_EMAIL_TEMPLATE = 'UPDATE_EMAIL_TEMPLATE';
export const UPDATE_EMAIL_TEMPLATE_SUCCESS = 'UPDATE_EMAIL_TEMPLATE_SUCCESS';
export const UPDATE_EMAIL_TEMPLATE_FAILED = 'UPDATE_EMAIL_TEMPLATE_FAILED';

export const DELETE_EMAIL_TEMPLATE = 'DELETE_EMAIL_TEMPLATE';
export const DELETE_EMAIL_TEMPLATE_SUCCESS = 'DELETE_EMAIL_TEMPLATE_SUCCESS';
export const DELETE_EMAIL_TEMPLATE_FAILED = 'DELETE_EMAIL_TEMPLATE_FAILED';
